# .github/actions/prepare-d2x-docker/action.yml
name: "Prepare D2X Docker"
description: "Pulls and caches D2X Docker image"
runs:
  using: "composite"
  steps:
    - name: Cache Docker images
      uses: actions/cache@v3
      with:
        path: /tmp/.docker-cache
        key: ${{ runner.os }}-docker-d2x-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-d2x-

    - name: Load cached Docker images
      shell: bash
      run: |
        if [ -f /tmp/.docker-cache/images.tar ]; then
          docker load < /tmp/.docker-cache/images.tar
        fi

    - name: Pull Docker image
      shell: bash
      run: |
        docker pull ghcr.io/muselab-d2x/d2x:cumulusci-next-snapshots
        docker save ghcr.io/muselab-d2x/d2x:cumulusci-next-snapshots > /tmp/.docker-cache/images.tar
