name: Beta Test 2GP

on:
    workflow_call:
        secrets:
            dev-hub-auth-url:
                required: true
            gh-email:
                required: true
            github-token:
                required: true

jobs:
    beta-test:
        name: "Beta Test Unlocked"
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/muselab-d2x/d2x:cumulusci-next-snapshots
            options: --user root
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.github-token }}
            env:
                DEV_HUB_AUTH_URL: "${{ secrets.dev-hub-auth-url }}"
                CUMULUSCI_SERVICE_github: '{ "username": "${{ github.actor }}", "token": "${{ secrets.github-token }}", "email": "${{ secrets.gh-email }}" }'
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Auth to DevHub
              run: /usr/local/bin/devhub.sh
            - name: Set default org
              run: cci org default beta
            - name: Build Beta Package
              run: cci flow run release_unlocked_beta
              shell: bash
            - name: Run Beta Test
              run: cci flow run ci_beta
            - name: Delete Scratch Org
              if: ${{ always() }}
              run: |
                  cci org scratch_delete beta
              shell: bash
