name: 2GP Feature Test and PR Snapshot
on:
    workflow_call:
        inputs:
            debug:
                required: false
                default: false
                type: boolean
            create_snapshot:
                required: false
                default: false
                type: boolean
            environment_prefix:
                required: false
                description: "If set, a GitHub Environment will be created for the snapshot with this prefix"
                type: string
        secrets:
            dev-hub-auth-url:
                required: false
            dev-hub-username:
                required: false
            dev-hub-client-id:
                required: false
            dev-hub-private-key:
                required: false
            gh-email:
                required: true
            github-token:
                required: true

jobs:
    feature-test-and-snapshot:
        name: "2GP Feature Test and PR Snapshot"
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/muselab-d2x/d2x:cumulusci-next
            options: --user root
            credentials:
                username: "${{ github.actor }}"
                password: "${{ secrets.github-token }}"
            env:
                DEV_HUB_AUTH_URL: "${{ secrets.dev-hub-auth-url }}"
                DEV_HUB_USERNAME: "${{ secrets.dev-hub-username }}"
                DEV_HUB_CLIENT_ID: "${{ secrets.dev-hub-client-id }}"
                DEV_HUB_PRIVATE_KEY: "${{ secrets.dev-hub-private-key }}"
                CUMULUSCI_SERVICE_github: '{ "username": "${{ github.actor }}", "token": "${{ secrets.github-token }}", "email": "${{ secrets.gh-email }}" }'
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Auth to DevHub
              run: /usr/local/bin/devhub.sh

            - name: Set feature org as default org
              run: |
                  cci org default feature
                  cci org info feature

            - name: Build Feature Test Package
              env:
                  GITHUB_TOKEN: "${{ secrets.github-token }}"
              run: cci flow run build_feature_test_package $([[ "${{ inputs.debug }}" == "true" ]] && echo " --debug") | tee cumulusci-flow.log
              shell: bash

            - name: Set Commit Status
              env:
                  GITHUB_TOKEN: "${{ secrets.github-token }}"
              run: |
                  VERSION=$(cat cumulusci-flow.log | grep -o -E -m 1 "04t[a-zA-Z0-9]{15}")
                  gh api \
                    --method POST \
                    -H "Accept: application/vnd.github.v3+json" \
                    '/repos/${{ github.repository }}/statuses/${{ github.sha }}' \
                    -f state='success' \
                    -f description="version_id: $VERSION" \
                    -f context='Build Feature Test Package'
              shell: bash

            - name: Run Feature Test
              id: feature_test
              env:
                  GITHUB_TOKEN: "${{ secrets.github-token }}"
              run: |
                  cci flow run ci_feature_2gp | tee feature-test.log
              continue-on-error: true

            - name: Run GitHub Pull Request Snapshot Task
              if: inputs.create_snapshot == true
              run: |
                  cci task run github_pull_request_snapshot \
                    --org feature \
                    --build_success ${{ job.status == 'success' }} \
                    --build_fail_tests ${{ contains(steps.feature_test.outputs.*, 'ApexTestException') }} \
                    --snapshot_is_packaged true \
                    $([[ -n "${{ inputs.environment_prefix }}" ]] && echo "--environment_prefix ${{ inputs.environment_prefix }}")
              shell: bash

            - name: Delete Scratch Org
              if: ${{ always() }}
              run: cci org scratch_delete feature
              shell: bash
