name: Org to GitHub Environment

on:
    workflow_call:
        inputs:
            org_alias:
                description: "Alias of the Salesforce org"
                required: true
                type: string
            environment_name:
                description: "Name of the GitHub environment to create"
                required: true
                default: ""
                type: string
            update_environment:
                description: "If true, the environment will be updated if it already exists"
                required: false
                default: false
                type: boolean
        secrets:
            github-token:
                required: true
            github-app-id:
                required: false
            github-app-key:
                required: false
            dev-hub-auth-url:
                required: false
            target-org-auth-url:
                required: false

jobs:
    org-to-env:
        name: "Org to GitHub Environment"
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/muselab-d2x/d2x:cumulusci-next-snapshots
            options: --user root
            credentials:
                username: "${{ github.actor }}"
                password: "${{ secrets.github-token }}"
            env:
                DEV_HUB_AUTH_URL: ${{ secrets.dev-hub-auth-url }}
                TARGET_ORG_AUTH_URL: ${{ secrets.target-org-auth-url }}
                GITHUB_APP_ID: ${{ secrets.github-app-id }}
                GITHUB_APP_KEY: ${{ secrets.github-app-key }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: actions/create-github-app-token@v1
              id: app-token
              with:
                app-id: ${{ secrets.github-app-id }}
                private-key: ${{ secrets.github-app-key }}
                owner: ${{ github.event.repository.owner.login }}
                repositories: |
                    ${{ github.event.repository.name }}

            - name: Check environment exists
              env:
                  GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
              run: |
                    gh api /repos/${{ github.repository }}/environments 2> /dev/null | jq -r '.total_count'
                    exists=`gh api /repos/${{ github.repository }}/environments/${{ inputs.environment_name }} 2> /dev/null | jq -r '.status'`
                    if [ "$exists" != "404" ]; then
                        if [ "${{ inputs.update_environment }}" = "true" ]; then
                            echo "Environment exists and will be updated"
                        else
                            echo "Environment already exists"
                            exit 1
                        fi
                    fi
            - name: Auth to DevHub
              run: /usr/local/bin/devhub.sh

            - name: Save Org to GitHub Environment
              if: always() && ${{ inputs.environment_name != '' }}
              uses: muselab-d2x/d2x-org-to-env@v1.1
              env:
                  GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
              with:
                org-alias: ${{ inputs.org_alias }}
                create-environment: 'true'
                environment-name: ${{ inputs.environment_name }}


