name: Org Login URL to Slack DM

on:
    workflow_call:
        inputs:
            environment:
                description: The name of the environment
                required: true
                type: string
            slack_username:
                description: Slack username to send the login URL
                required: true
                type: string
        secrets:
            slack-bot-token:
                required: true
            github-token:
                required: true

jobs:
    d2x-login-url:
        name: Use d2x to generate a login url
        runs-on: ubuntu-latest
        environment: ${{ github.event.inputs.environment }}
        steps:
            - run: pip install git+https://github.com/muselab-d2x/d2x.git@jlantz/update-auth-structure

            - id: generate_login_url
              name: Generate Login URL for ${{ github.event.inputs.environment }}
              env:
                  SFDX_AUTH_URL: ${{ secrets.sfdx-auth-url }}
              run: |
                  set -eo pipefail
                  d2x sf auth login | tail -1 > login_url.txt

            - name: Send Slack DM
              if: success()
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}
              run: |
                  echo "login_url=$(cat login_url.txt)" >> $GITHUB_OUTPUT
                  rm login_url.txt
                  curl -X POST -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
                       -H "Content-Type: application/json" \
                       -d '{
                         "channel": "@${{ github.event.inputs.slack_username }}",
                         "text": "Here'"'"'s your Salesforce login URL for ${{ github.event.inputs.environment }}: ${{ steps.generate_login_url.outputs.login_url }}"
                       }' \
                       https://slack.com/api/chat.postMessage
