name: Org to GitHub Environment

on:
    workflow_call:
        inputs:
            org_alias:
                description: "Alias of the Salesforce org"
                required: true
                type: string
            environment_name:
                description: "Name of the GitHub environment to create"
                required: true
                default: ""
                type: string
            update_environment:
                description: "If true, the environment will be updated if it already exists"
                required: false
                default: false
                type: boolean
            secrets:
                github-token:
                    required: true
                github-app-id:
                    required: false
                github-app-key:
                    required: false
                dev-hub-auth-url:
                    required: false
                target-org-auth-url:
                    required: false

jobs:
    org-to-env:
        name: "Org to GitHub Environment"
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/muselab-d2x/d2x:cumulusci-next-snapshots
            options: --user root
            credentials:
                username: "${{ github.actor }}"
                password: "${{ secrets.github-token }}"
            env:
                DEV_HUB_AUTH_URL: ${{ secrets.dev-hub-auth-url }}
                TARGET_ORG_AUTH_URL: ${{ secrets.target-org-auth-url }}
                GITHUB_APP_ID: ${{ secrets.github-app-id }}
                GITHUB_APP_KEY: ${{ secrets.github-app-key }}
                GITHUB_TOKEN: ${{ secrets.github-token }}

        steps:
            - name: Check environment exists
              run: |
                    gh api /repos/${{ github.repository }}/environments/${{ inputs.environment_name }} --silent
                    if [ $? -eq 0 ]; then
                        if [ "${{ inputs.update_environment }}" = "true" ]; then
                            echo "Environment exists and will be updated"
                        else
                            echo "Environment already exists"
                            exit 1
                        fi
                    fi
            - name: Auth to DevHub
              run: /usr/local/bin/devhub.sh

            - name: Save Org to GitHub Environment
              if: always() && ${{ inputs.environment_name != '' }}
              uses: muselab-d2x/d2x-org-to-env@v1.1
              env:
                  GITHUB_APP_ID: ${{ secrets.github-app-id }}
                  GITHUB_APP_KEY: ${{ secrets.github-app-key }}
                  GITHUB_TOKEN: ${{ secrets.github-token }}
              with:
                org-alias: ${{ inputs.org }}
                create-environment: 'true'
                environment-name: ${{ inputs.environment_name }}


