name: Python Tests

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: actions/starter-workflows/.github/workflows/python-tests.yml@main
    with:
      python-version: '3.10'
