name: Production Release

on:
    workflow_call:
        inputs:
            env-name:
                required: true
                type: string
            debug:
                required: false
                default: false
                type: boolean
        secrets:
            dev-hub-auth-url:
                required: true
            packaging-org-auth-url:
                required: true
            gh-email:
                required: true
            github-token:
                required: true

jobs:
    release-test:
        name: "Production Release"
        runs-on: ubuntu-latest
        environment: ${{ inputs.env-name }}
        container:
            image: ghcr.io/muselab-d2x/d2x:cumulusci-next-snapshots
            options: --user root
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.github-token }}
            env:
                DEV_HUB_AUTH_URL: "${{ secrets.dev-hub-auth-url }}"
                PACKAGING_ORG_AUTH_URL: "${{ secrets.packaging-org-auth-url }}"
                CUMULUSCI_SERVICE_github: '{ "username": "${{ github.actor }}", "token": "${{ secrets.github-token }}", "email": "${{ secrets.gh-email }}" }'
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Auth to DevHub
              run: /usr/local/bin/devhub.sh
            - name: Deploy to Packaging Org
              run: cci flow run ci_master --org packaging
            - name: Build Production Package
              run: cci flow run release_production --org packaging $([[ "${{ inputs.debug }}" == "true" ]] && echo " --debug")
              shell: bash
            - name: Run Release Test
              run: cci flow run ci_release --org release $([[ "${{ inputs.debug }}" == "true" ]] && echo " --debug")
            - name: Delete Scratch Org
              if: ${{ always() }}
              run: |
                  cci org scratch_delete release
              shell: bash
