name: Production Release

on:
    workflow_call:
        inputs:
            release-name:
                required: false
                description: "The name of the release to upload to the production org."
                type: string
            skip-deploy:
                required: false
                description: If true, don't deploy to the packaging org. Just release what's in the org currently
                type: boolean
                default: false
            skip-test:
                required: false
                description: If true, don't test the package. Just upload and pass the build if the upload and GitHub Release are created successfully
                type: boolean
                default: false    
        secrets:
            dev-hub-auth-url:
                required: true
            packaging-org-auth-url:
                required: true
            gh-email:
                required: true
            github-token:
                required: true

jobs:
    release-test:
        name: "Production Release"
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/muselab-d2x/d2x:cumulusci-next
            options: --user root
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.github-token }}
            env:
                DEV_HUB_AUTH_URL: "${{ secrets.dev-hub-auth-url }}"
                PACKAGING_ORG_AUTH_URL: "${{ secrets.packaging-org-auth-url }}"
                CUMULUSCI_SERVICE_github: '{ "username": "${{ github.actor }}", "token": "${{ secrets.github-token }}", "email": "${{ secrets.gh-email }}" }'
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Auth to DevHub
              run: /usr/local/bin/devhub.sh
            - name: Report Inputs
              run: |
                echo "Release Name: ${{ inputs.release-name }}" | tee -a "${GITHUB_STEP_SUMMARY}"
                echo 'Command: cci flow run release_production --org packaging $([[ "${{ inputs.release-name }}" ]] && echo " -o upload_production__version_name_template \\"${{ inputs.release-name }}\\"")' | tee -a "${GITHUB_STEP_SUMMARY}"
            - name: Deploy to Packaging Org
              if: ${{ inputs.skip-deploy == false }}
              run: cci flow run ci_master --org packaging
            - name: Build Production Package
              run: eval $(echo cci flow run release_production --org packaging $([[ "${{ inputs.release-name }}" ]] && echo " -o upload_production__version_name_template \\"${{ inputs.release-name }}\\"))
              shell: bash
            - name: Run Release Test in Scratch Org
              if: ${{ inputs.skip-test == false }}
              run: cci flow run ci_release --org release
            - name: Delete Scratch Org
              if: ${{ always() }} && ${{ inputs.skip-test == false }}
              run: |
                  cci org scratch_delete release
              shell: bash
