name: Run Tests
on:
    push:
        branches:
            - "**"
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                  version: 1.7.1
                  virtualenvs-create: true
                  virtualenvs-in-project: true

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      .venv
                      ~/.cache/pypoetry
                  key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-poetry-

            - name: Install dependencies
              run: |
                  poetry install --with dev

            - name: Run tests
              run: |
                  poetry run pytest tests/
